-- MySQL Script generated by MySQL Workbench
-- Sun 12 Apr 2015 09:56:22 PM EDT
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema player
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `player` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `player` ;

-- -----------------------------------------------------
-- Table `player`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `player`.`player` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `homepage` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `userName_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
