-- MySQL Script generated by MySQL Workbench
-- Mon 13 Apr 2015 11:34:02 AM EDT
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `service` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `service` ;

-- -----------------------------------------------------
-- Table `service`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service`.`service` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` TINYTEXT NULL,
  `url` VARCHAR(255) NULL,
  `status` ENUM('open','closed') NULL,
  `type` ENUM('user','subdirectory','game','other') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
