-- MySQL Script generated by MySQL Workbench
-- Sun 12 Apr 2015 09:53:01 PM EDT
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tictactoe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tictactoe` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `tictactoe` ;

-- -----------------------------------------------------
-- Table `tictactoe`.`tictactoe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tictactoe`.`tictactoe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` ENUM('offered','playing','won first','won second','draw') NULL DEFAULT 'offered',
  `firstplayername` VARCHAR(45) NOT NULL,
  `secondplayername` VARCHAR(45) NULL,
  `playerturn` ENUM('first','second') NULL DEFAULT 'first',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tictactoe`.`cell`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tictactoe`.`cell` (
  `id` TINYINT NOT NULL,
  `tictactoe_id` INT NOT NULL,
  `mark` ENUM('x','o') NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `tictactoe_id`),
  INDEX `fk_tictactoe_cell_tictactoe1_idx` (`tictactoe_id` ASC),
  CONSTRAINT `fk_tictactoe_cell_tictactoe1`
    FOREIGN KEY (`tictactoe_id`)
    REFERENCES `tictactoe`.`tictactoe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
